[package]
name = "wvc-provider-env"
version = "0.1.0"
edition = "2024"

[lib]
name = "wvc_provider_env"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
wvc-core = { path = "../wvc-core" }
wvc-logging = { path = "../wvc-logging" }
wvc-provider-metadata = { path = "../wvc-provider-metadata" }
wvc-storage = { path = "../wvc-storage" }

[dev-dependencies]
tempfile = "3"
