name: matrix-test
on:
  workflow_dispatch:

jobs:
  matrix-jobs:
    name: Matrix (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [self-hosted, linux, x64]
            label: linux-local
          - os: macos-latest
            label: macos-cloud
    steps:
      - run: echo "Running on ${{ matrix.label }} | runner=${{ runner.name }}"
